spring:
  application:
    name: skill-service
  config:
    import: optional:configserver:http://config-server:8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
